after_failure:
  - mysql -e 'show databases;'
  - cat ./config/database.yml
  - echo $RAILS_ENV
  - bundle exec rake --version
  - ruby env
before_script:
  - cp config/database.yml.example config/database.yml
  - cp config/initializers/01_mygov.rb.example config/initializers/01_mygov.rb
  - cp config/resque.yml.example config/resque.yml
  - sed -i.bak 's/PUT YOUR SECRET TOKEN HERE/868b2bada3124d10aa96b3793d3e1419e95991c4f4995494e460025d487792effcb17e21bbd3338b4dcf1a250fa693ba52a6a5e3518db9f98f509a446ab48e45/g' config/initializers/01_mygov.rb
  - mysql -e 'create database mygov_test;'
install:
  - bundle install --without development
language: ruby
notifications:
  email:
    recipients:
      - alison.rowland@gsa.gov
      - amos.stone@businessusa.gov
      - gregory.gershman@gsa.gov
      - john.felleman@gsa.gov
      - john.kemp@gsa.gov
      - justin.grevich@gsa.gov
      - raphael.villas@gsa.gov
      - mike@mobomo.com
      - adam@mobomo.com
script:
  - bundle exec rake db:schema:load
  - bundle exec rake db:test:prepare
  - bundle exec rake spec
services:
  - mysql
  - redis-server
rvm:
  - 2.1.1
  - 2.0.0
  - 1.9.3
branches:
  only:
    - master
    - xavier
    - /.*-travis$/
env:
  - RECAPTCHA_PUBLIC_KEY='6Lc-1-USAAAAABEnLWm2KRTQ90f41UgFneddln9_' RECAPTCHA_PRIVATE_KEY='6Lc-1-USAAAAAC9n2SlCH7AgAsVyS9K-PLOH8gbs'